title: Set the pins for a single button
hero_image: images/banner.png
description: single-button-pins description
version: 4
listed: false
copyedit: false
last_tested: "2022-02-14"
steps:
  - title: Introduction
  - title: Step title
  - title: What next?
