title: Set the pins for a single button
hero_image: images/banner.png
description: How to set the pins for a single button on your Raspberry Pi Pico
version: 4
listed: false
copyedit: false
last_tested: "2022-02-14"
steps:
  - title: Set the pins for a single button
